"""Constants for the HA InMet Alerts integration."""

DOMAIN = "inmet"
COORDINATOR = "coordinator"

NAME = "name"
GEOCODE = "geocode"

FIELD_ID = "id"
FIELD_ID_ALERT = "id_aviso"
FIELD_SEQUENCE = "id_sequencia"
FIELD_START_DATE = "data_inicio"
FIELD_START_TIME = "hora_inicio"
FIELD_END_DATE = "data_fim"
FIELD_END_TIME = "hora_fim"
FIELD_UPDATED = "alterado"
FIELD_FINISHED = "encerrado"
FIELD_CREATED_AT = "created_at"
FIELD_UPDATED_AT = "updated_at"
FIELD_START = "inicio"
FIELD_FINISH = "fim"
FIELD_ICON = "icone"
FIELD_DESCRIPTION = "descricao"
FIELD_WARNING_COLOR = "aviso_cor"
FIELD_ID_SEVERITY = "id_severidade"
FIELD_SEVERITY = "severidade"
FIELD_RISKS = "riscos"
FIELD_INSTRUCTIONS = "instrucoes"
FIELD_FUTURE = "future"
